name: iptv_flutter
description: "A comprehensive Flutter IPTV application with multi-profile support and smart caching."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & Network
  http: ^1.2.1
  dio: ^5.4.3+1
  
  # Video Player
  video_player: ^2.8.6
  chewie: ^1.8.1
  
  # Database & Storage
  sqflite: ^2.3.3+1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # UI & Images
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  
  # Icons & Fonts
  cupertino_icons: ^1.0.8
  
  # Utilities
  connectivity_plus: ^6.0.3
  url_launcher: ^6.2.6
  intl: ^0.19.0
  
  # Environment Variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
